name: Rust CI

on:
  push:
    paths:
      - .github/workflows/rust_ci.yml
      - rs/**
  pull_request:
    paths:
      - .github/workflows/rust_ci.yml
      - rs/**

jobs:
  build_and_test:
    name: Rust Cargo CI on ${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Verify Cargo.toml
        uses: actions-rs/cargo@v1
        with:
          command: verify-project
          args: --manifest-path rs/Cargo.toml

      - name: Cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path rs/Cargo.toml --check

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path rs/Cargo.toml

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path rs/Cargo.toml

      - name: Cargo release + all feature build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path rs/Cargo.toml --release --all-features
