name: Rust CI

on: [push, pull_request]

defaults:
 run:
  working-directory: ./rs

jobs:
  build_and_test:
    name: Rust Cargo project CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Cargo release + all feature build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
